/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/steak.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.3, 0.39, 0.01]}>
        <group position={[0.3, -0.39, -0.01]}>
          <mesh geometry={nodes['node-0'].geometry} material={materials.map_Ka} />
        </group>
      </group>
      <group position={[-6.95, 0.67, -2.94]} rotation={[1.59, -0.04, 1.99]} />
    </group>
  )
}

useGLTF.preload('/steak.glb')
